#!/bin/bash
set -e

REGION=us-east-1
IMAGE_URI=$(python3 -c "import json; print(json.load(open('/app/deployment/imageDetail.json'))['ImageURI'])")
ECR_HOST=$(echo $IMAGE_URI | cut -d'/' -f1)

aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_HOST
docker pull $IMAGE_URI